#!/usr/bin/env python3
"""Generate the shipped runtime step catalog from the coverage inventory."""
import argparse
import hashlib
import json
from pathlib import Path
import pprint
from check_coverage import OBSERVATION_CONTRACT, inventory_report, validate_manifest

ROOT = Path(__file__).resolve().parents[2]


def render_catalog(root=ROOT):
    inventory = json.loads((root / 'tests/skill_coverage.json').read_text())
    validate_manifest(inventory, root)
    skills = {}
    for name, skill in inventory['skills'].items():
        sources = {skill['source']} | {s['requirement']['path'] for s in skill['steps']}
        skills[name] = {
            'version': (root / 'skills' / name / 'VERSION').read_text().strip(),
            'source_digests': {p: hashlib.sha256((root / p).read_bytes()).hexdigest() for p in sorted(sources)},
            'steps': [{key: step[key] for key in ('id', 'title', 'applies_when', 'expected_evidence')}
                      for step in skill['steps']],
        }
    return ('"""Generated by scripts/verify/build_step_catalog.py; do not edit."""\n\n'
            + 'OBSERVATION_CONTRACT = ' + pprint.pformat(OBSERVATION_CONTRACT, width=110, sort_dicts=False) + '\n\n'
            + 'SKILLS = ' + pprint.pformat(skills, width=110, sort_dicts=False) + '\n')


def render_coverage_summary(root=ROOT):
    inventory = json.loads((root / 'tests/skill_coverage.json').read_text())
    report = inventory_report(inventory)
    lines = ['<!-- skill-coverage:start -->',
             'This inventory maps requirements to checks; it does not record test executions or pass rates.', '',
             '| Skill | Steps | Validator mappings | Component case mappings | Manual case mappings | Steps with gaps |',
             '|---|---:|---:|---:|---:|---:|']
    for name, summary in report['skills'].items():
        values = [summary[k] for k in ('steps', 'with_validators', 'with_automated_component_cases',
                                      'with_manual_agent_cases', 'with_gaps')]
        lines.append('| ' + name + ' | ' + ' | '.join(map(str, values)) + ' |')
    lines.extend(['', f"Runtime capture: `{OBSERVATION_CONTRACT['capture_kind']}`. "
                  + OBSERVATION_CONTRACT['fully_observed_meaning'], '',
                  'Recorded completion does not verify behavior or quality. Recording order does not prove execution order. '
                  'Step observations do not affect delivery gates.', '<!-- skill-coverage:end -->'])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render_catalog()
    paths = [ROOT / 'src/ship/lifecycle/step_catalog.py', ROOT / 'skills/ship/scripts/lifecycle/step_catalog.py']
    readme = ROOT / 'README.md'
    contents = readme.read_text()
    start = contents.index('<!-- skill-coverage:start -->')
    end = contents.index('<!-- skill-coverage:end -->') + len('<!-- skill-coverage:end -->')
    expected_readme = contents[:start] + render_coverage_summary() + contents[end:]
    if args.check:
        stale = [str(p.relative_to(ROOT)) for p in paths if not p.exists() or p.read_text() != expected]
        if contents != expected_readme:
            stale.append('README.md coverage summary')
        if stale:
            print('Stale runtime step catalog: ' + ', '.join(stale))
            return 1
    else:
        for path in paths:
            path.write_text(expected)
        readme.write_text(expected_readme)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
