#!/usr/bin/env python3
"""Generate the shipped runtime step catalog from the coverage inventory."""
import argparse
import hashlib
import json
from pathlib import Path
import pprint

ROOT = Path(__file__).resolve().parents[2]


def render_catalog(root=ROOT):
    inventory = json.loads((root / 'tests/skill_coverage.json').read_text())
    skills = {}
    for name, skill in inventory['skills'].items():
        sources = {skill['source']} | {s['requirement']['path'] for s in skill['steps']}
        skills[name] = {
            'version': (root / 'skills' / name / 'VERSION').read_text().strip(),
            'source_digests': {p: hashlib.sha256((root / p).read_bytes()).hexdigest() for p in sorted(sources)},
            'steps': [{key: step[key] for key in ('id', 'title', 'applies_when', 'expected_evidence')}
                      for step in skill['steps']],
        }
    return ('"""Generated by scripts/verify/build_step_catalog.py; do not edit."""\n\n'
            + 'SKILLS = ' + pprint.pformat(skills, width=110, sort_dicts=False) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render_catalog()
    paths = [ROOT / 'src/ship/lifecycle/step_catalog.py', ROOT / 'skills/ship/scripts/lifecycle/step_catalog.py']
    if args.check:
        stale = [str(p.relative_to(ROOT)) for p in paths if not p.exists() or p.read_text() != expected]
        if stale:
            print('Stale runtime step catalog: ' + ', '.join(stale))
            return 1
    else:
        for path in paths:
            path.write_text(expected)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
