#!/usr/bin/env bun
import { copyFile, mkdir, readFile, readdir, stat } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';

const TOOL_MODULES: Record<string, [string, string]> = {
  debug: ['src/ship/tools/debug.ts', 'skills/debug/scripts/verify_fix.ts'], design: ['src/ship/tools/design.ts', 'skills/design/scripts/validate_design.ts'], evals: ['src/ship/tools/evals.ts', 'skills/evals/scripts/score_calibration.ts'], sample_traces: ['src/ship/tools/sample_traces.ts', 'skills/evals/scripts/sample_traces.ts'], simplify: ['src/ship/tools/simplify.ts', 'skills/simplify/scripts/scan_debt.ts'], skill: ['src/ship/tools/skill.ts', 'skills/skill/scripts/validate_skill.ts'], tdd: ['src/ship/tools/tdd.ts', 'skills/tdd/scripts/verify_tdd.ts'], review: ['src/ship/tools/review.ts', 'skills/review/scripts/validate_report.ts'], spike: ['src/ship/tools/spike.ts', 'skills/spike/scripts/run_spike.ts'], ux: ['src/ship/tools/ux.ts', 'skills/ux/scripts/audit_ux.ts'],
};
export async function findRepoRoot(start = process.cwd()) { let p = resolve(start); while (true) { try { await stat(join(p, 'src/ship')); await stat(join(p, 'skills')); return p; } catch {} const parent = resolve(p, '..'); if (parent === p) return resolve(start); p = parent; } }
export async function getFileMappings(root: string): Promise<[string, string][]> { const out: [string, string][] = []; const lifecycle = await readdir(join(root, 'src/ship/lifecycle')); for (const f of lifecycle.filter((x) => x.endsWith('.py')).sort()) out.push([join(root, 'src/ship/lifecycle', f), join(root, 'skills/ship/scripts/lifecycle', f)]); for (const pair of Object.values(TOOL_MODULES)) out.push(pair.map((x) => join(root, x)) as [string, string]); out.push([join(root, 'src/ship/tool_runtime.py'), join(root, 'skills/ship/scripts/tool_runtime.py')]); const tools = await readdir(join(root, 'src/ship/tools')); for (const f of tools.filter((x) => x.endsWith('.ts') && !x.startsWith('claude_')).sort()) out.push([join(root, 'src/ship/tools', f), join(root, 'skills/ship/scripts/tools', f)]); for (const skill of ['tdd', 'simplify']) out.push([join(root, 'src/ship/tools/python_source.ts'), join(root, `skills/${skill}/scripts/python_source.ts`)]); return out; }
export async function checkParity(root: string) { const errors: string[] = []; for (const [src, dest] of await getFileMappings(root)) { let a: Buffer, b: Buffer; try { a = await readFile(src); } catch { errors.push(`Missing source file: ${relative(root, src)}`); continue; } try { b = await readFile(dest); } catch { errors.push(`Missing skills file: ${relative(root, dest)}`); continue; } if (!a.equals(b)) errors.push(`Parity mismatch: ${relative(root, src)} != ${relative(root, dest)}`); } return [errors.length === 0, errors] as const; }
export async function syncFiles(root: string, direction: 'src-to-skills' | 'skills-to-src' = 'src-to-skills') { const synced: [string, string][] = []; for (const [src, dest] of await getFileMappings(root)) { const [from, to] = direction === 'src-to-skills' ? [src, dest] : [dest, src]; await mkdir(resolve(to, '..'), { recursive: true }); await copyFile(from, to); synced.push([from, to]); } return synced; }

if (import.meta.main) { const args = Bun.argv.slice(2); const check = args.includes('--check') || args.includes('--verify'); const quiet = args.includes('-q') || args.includes('--quiet'); const direction = (args.includes('--direction') ? args[args.indexOf('--direction') + 1] : 'src-to-skills') as 'src-to-skills' | 'skills-to-src'; const pathArg = args.includes('--path') ? args[args.indexOf('--path') + 1] : undefined; const root = await findRepoRoot(pathArg); if (check) { const [passed, errors] = await checkParity(root); if (passed) { if (!quiet) console.log(`Parity check passed: all ${(await getFileMappings(root)).length} files are byte-for-byte identical.`); process.exit(0); } console.error(`Parity check failed: ${errors.length} divergence(s) detected.\n\n${errors.join('\n')}`); process.exit(1); } const synced = await syncFiles(root, direction); if (!quiet) console.log(`Synchronized ${synced.length} file(s) (${direction}).`); }
