"""Ship Lifecycle Engine Package."""

from .checkpoints import CheckpointManager
from .config import ShipConfigManager
from .engine import LifecycleEngine, format_summary
from .evidence import (
    inspect_review_reports,
    inspect_spikes,
    is_spike_completed,
    is_test_evidence_passing,
    validate_judge_report_contract,
    validate_review_approval,
)
from .gates import determine_lifecycle_state, validate_delivery_readiness
from .models import (
    GateResult, GateStatus, GitInfo, LifecyclePhase, OpenSpecInfo, ShipConfig, VerificationResult,
    VerificationRecord, VerificationTier, StagnationType, TurnContract, TurnRecord,
    LeaseStatus, CoordinationConflictType, TaskLease, TaskHandoff,
    AgentRole, AgentIdentity, AgentSession, ActionProvenance,
    CapabilityOperation, ExecutionRing, Capability, AccessDecision,
)
from .capabilities import (
    CapabilityManager,
)
from .provenance import (
    ProvenanceManager,
    compute_payload_digest,
)
from .coordination import (
    CoordinationConfig,
    CoordinationManager,
    CoordinationResult,
    is_lease_expired,
)
from .convergence import (
    ConvergenceConfig,
    ConvergenceController,
    ConvergenceStatus,
    evaluate_convergence,
    detect_same_evidence,
    detect_same_finding,
    detect_same_patch,
    detect_same_verifier_failure,
    detect_oscillating_state,
)
from .verification import (
    parse_line_range,
    verify_finding_grounding,
    verify_review_grounding,
    execute_and_verify_tests,
    verify_test_quality,
    verify_spec_coverage,
    run_gate_verification,
    format_verification_summary,
    validate_walkthrough_report,
)

from .ledger import FileLedgerStore, record_turn_to_ledger, get_turns_from_ledger
from .turns import get_next_turn_contract, format_turn_contract, format_turns_log, resolve_skill_name
from .specs import OpenSpecRepository, merge_spec_requirements, normalize_req_title, parse_requirements_doc
from .trailers import CommitTrailerGenerator, canonicalize_gate_name
from .vcs import GIT_NOTES_REF, GitClient
from .events import (
    EventLogger,
    EventReplayer,
    compute_event_hash,
)
from .resources import (
    BudgetStatus,
    ChangeBudget,
    ResourceGovernor,
    ResourceMetric,
    ResourceUsage,
)
from .evaluation import (
    BenchmarkDimension,
    EvaluationReport,
    EvaluationRunner,
    ScenarioResult,
    run_all_benchmarks,
)

__all__ = [
    "BenchmarkDimension",
    "BudgetStatus",
    "ChangeBudget",
    "EventLogger",
    "EventReplayer",
    "compute_event_hash",
    "ResourceGovernor",
    "ResourceMetric",
    "ResourceUsage",
    "EvaluationReport",
    "EvaluationRunner",
    "ScenarioResult",
    "run_all_benchmarks",
    "AccessDecision",
    "ActionProvenance",
    "AgentIdentity",
    "AgentRole",
    "AgentSession",
    "Capability",
    "CapabilityManager",
    "CapabilityOperation",
    "ExecutionRing",
    "CheckpointManager",
    "CommitTrailerGenerator",
    "CoordinationConfig",
    "CoordinationManager",
    "CoordinationResult",
    "ConvergenceConfig",
    "ConvergenceController",
    "ConvergenceStatus",
    "FileLedgerStore",
    "GIT_NOTES_REF",
    "GateResult",
    "GateStatus",
    "GitClient",
    "GitInfo",
    "LeaseStatus",
    "CoordinationConflictType",
    "ProvenanceManager",
    "TaskLease",
    "TaskHandoff",
    "compute_payload_digest",
    "is_lease_expired",
    "LifecycleEngine",
    "LifecyclePhase",
    "OpenSpecInfo",
    "OpenSpecRepository",
    "ShipConfig",
    "ShipConfigManager",
    "StagnationType",
    "TurnContract",
    "TurnRecord",
    "VerificationRecord",
    "VerificationResult",
    "VerificationTier",
    "detect_oscillating_state",
    "detect_same_evidence",
    "detect_same_finding",
    "detect_same_patch",
    "detect_same_verifier_failure",
    "evaluate_convergence",
    "OpenSpecInfo",
    "OpenSpecRepository",
    "ShipConfig",
    "ShipConfigManager",
    "TurnContract",
    "TurnRecord",
    "VerificationRecord",
    "VerificationResult",
    "VerificationTier",
    "execute_and_verify_tests",
    "format_verification_summary",
    "parse_line_range",
    "run_gate_verification",
    "verify_finding_grounding",
    "verify_review_grounding",
    "verify_spec_coverage",
    "verify_test_quality",
    "canonicalize_gate_name",
    "determine_lifecycle_state",
    "format_summary",
    "format_turn_contract",
    "format_turns_log",
    "get_next_turn_contract",
    "get_turns_from_ledger",
    "inspect_review_reports",
    "inspect_spikes",
    "is_spike_completed",
    "is_test_evidence_passing",
    "merge_spec_requirements",
    "normalize_req_title",
    "parse_requirements_doc",
    "record_turn_to_ledger",
    "resolve_skill_name",
    "validate_delivery_readiness",
    "validate_judge_report_contract",
    "validate_review_approval",
]
