"""State ledger persistence and workspace synchronization."""

from contextlib import contextmanager
import json
import os
from pathlib import Path
import tempfile
import threading
import time
from typing import Any, Callable, Dict, List, Optional

from .evidence import (
    validate_review_approval, is_test_evidence_passing, implementation_failed,
    design_fingerprint, validate_design_approval, inspect_spikes,
)
from .vcs import GitClient
from .paths import (
    repository_path, validate_change_id, agentflow_path,
    get_state_file, get_lock_file, get_checkpoints_dir,
)
from .transactions import recover_archive, sync_directory

try:
    import fcntl
except ImportError:
    fcntl = None  # type: ignore

_tls = threading.local()


def read_json_file(path: Path, default: Any = None) -> Any:
    """Safely load JSON from file path, returning default on missing file or parse error."""
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def read_ledger_file(path: Path) -> Optional[Dict[str, Any]]:
    """Distinguish first use from damaged authoritative state; never repair implicitly."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None
    except (ValueError, OSError) as exc:
        raise ValueError(f"Cannot read ledger {path}; preserved unchanged. Restore a known-good copy or explicitly move it aside before --sync-state: {exc}") from exc
    valid = (
        isinstance(data, dict) and data.get("version", 1) == 1
        and isinstance(data.get("changes"), dict)
        and (data.get("active_change_id") is None or isinstance(data.get("active_change_id"), str))
    )
    if valid:
        for cid, entry in data["changes"].items():
            if not isinstance(cid, str) or not isinstance(entry, dict):
                valid = False
                break
            for key, kind in (("task_status", dict), ("evidence", dict), ("verification", dict), ("checkpoints", dict), ("blockers", list), ("turns", list)):
                if key in entry and not isinstance(entry[key], kind):
                    valid = False
            if isinstance(entry.get("blockers", []), list) and any(not isinstance(b, str) for b in entry.get("blockers", [])):
                valid = False
            if isinstance(entry.get("turns", []), list) and any(not isinstance(t, dict) for t in entry.get("turns", [])):
                valid = False
            revision = entry.get("revision_counter", 0)
            if type(revision) is not int or revision < 0:
                valid = False
            if isinstance(entry.get("evidence", {}), dict) and any(not isinstance(ev, dict) for ev in entry.get("evidence", {}).values()):
                valid = False
    if not valid:
        raise ValueError(f"Invalid ledger schema in {path}; preserved unchanged. Restore a known-good copy or explicitly move it aside before --sync-state.")
    return data


def ensure_gitignore_has_agentflow(repo_root: Path) -> None:
    """Ensure .agentflow/ is ignored in git without creating unwanted untracked working-tree files."""
    def _append_ignore_entry(target: Path) -> bool:
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            content = target.read_text(encoding="utf-8") if target.exists() else ""
            lines = [l.strip() for l in content.splitlines()]
            if ".agentflow" not in lines and ".agentflow/" not in lines:
                with target.open("a", encoding="utf-8") as f:
                    if content and not content.endswith("\n"):
                        f.write("\n")
                    f.write(".agentflow/\n")
            return True
        except Exception:
            return False

    info_exclude = repo_root / ".git" / "info" / "exclude"
    appended = False
    if info_exclude.parent.exists():
        appended = _append_ignore_entry(info_exclude)
    if not appended:
        _append_ignore_entry(repo_root / ".gitignore")


ensure_gitignore_has_ship = ensure_gitignore_has_agentflow


def is_review_blocker(blocker: str) -> bool:
    """Check if a blocker string is generated by review evaluations."""
    return (
        blocker.startswith("Review:")
        or blocker.startswith("Review has ")
        or blocker.startswith("Review verdict is ")
    )


def make_default_review_evidence() -> Dict[str, Any]:
    """Default review evidence structure."""
    return {
        "verdict": None,
        "status": "PENDING",
        "findings_count": 0,
        "critical_or_high_count": 0,
        "reviewer": None,
        "report_path": None,
        "snapshot_sha": None,
        "snapshot_fingerprint": None,
        "test_evidence_passed": None,
    }


def make_default_evidence() -> Dict[str, Any]:
    return {
        "design": {"adr": None, "status": "PENDING"},
        "spike": {"status": "NONE", "verdict": None, "dir": None},
        "implementation": {"status": "PENDING", "tests_passed": None, "failed_count": 0},
        "simplify": {"debt_count": 0, "status": "PENDING"},
        "review": make_default_review_evidence(),
        "delivery": {"status": "PENDING"},
    }


def create_empty_change_entry(change_id: str) -> Dict[str, Any]:
    return {
        "change_id": change_id,
        "phase": "design",
        "task_status": {
            "total": 0,
            "completed": 0,
            "pending": 0,
            "next": None,
            "in_progress": None,
        },
        "blockers": [],
        "revision_counter": 0,
        "evidence": make_default_evidence(),
        "verification": {},
        "checkpoints": {},
        "turns": [],
    }


class FileLedgerStore:
    """Thread-safe, atomic state store for .agentflow/state.json."""

    @staticmethod
    def get_ledger_path(repo_root: Path) -> Path:
        return get_state_file(repo_root)

    @classmethod
    @contextmanager
    def lock(cls, repo_root: Path, timeout_sec: float = 10.0):
        agentflow_dir = agentflow_path(repo_root)
        agentflow_dir.mkdir(parents=True, exist_ok=True)
        sync_directory(repo_root)
        lock_file = get_lock_file(repo_root).resolve()
        lock_key = str(lock_file)

        if not hasattr(_tls, "locks"):
            _tls.locks = {}

        current_depth = _tls.locks.get(lock_key, 0)
        if current_depth > 0:
            _tls.locks[lock_key] = current_depth + 1
            try:
                yield
            finally:
                _tls.locks[lock_key] -= 1
            return

        fd = os.open(str(lock_file), os.O_RDWR | os.O_CREAT, 0o666)
        locked = False
        try:
            if fcntl:
                start_time = time.time()
                while True:
                    try:
                        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                        locked = True
                        break
                    except (BlockingIOError, IOError, OSError):
                        if time.time() - start_time >= timeout_sec:
                            fcntl.flock(fd, fcntl.LOCK_EX)
                            locked = True
                            break
                        time.sleep(0.01)
            _tls.locks[lock_key] = 1
            recover_archive(repo_root)
            yield
        finally:
            _tls.locks[lock_key] = 0
            if locked and fcntl:
                try:
                    fcntl.flock(fd, fcntl.LOCK_UN)
                except Exception:
                    pass
            try:
                os.close(fd)
            except Exception:
                pass

    @classmethod
    def get_active_change(cls, repo_root: Path) -> Optional[str]:
        with cls.lock(repo_root):
            ledger_data = read_ledger_file(cls.get_ledger_path(repo_root))
            if isinstance(ledger_data, dict) and ledger_data.get("active_change_id"):
                return validate_change_id(ledger_data["active_change_id"])
            return None

    @classmethod
    def save(cls, repo_root: Path, ledger: Dict[str, Any]) -> None:
        with cls.lock(repo_root):
            read_ledger_file(cls.get_ledger_path(repo_root))
            agentflow_dir = agentflow_path(repo_root)
            agentflow_dir.mkdir(parents=True, exist_ok=True)
            ensure_gitignore_has_agentflow(repo_root)
            ledger_path = cls.get_ledger_path(repo_root)

            temp_fd, temp_path = tempfile.mkstemp(prefix="state_", suffix=".json.tmp", dir=str(agentflow_dir))
            try:
                with os.fdopen(temp_fd, "w", encoding="utf-8") as f:
                    json.dump(ledger, f, indent=2)
                    f.flush()
                    os.fsync(f.fileno())
                os.replace(temp_path, ledger_path)
                sync_directory(ledger_path.parent)
            except Exception:
                if os.path.exists(temp_path):
                    try:
                        os.remove(temp_path)
                    except Exception:
                        pass
                raise

    @classmethod
    def sync_from_workspace(
        cls,
        repo_root: Path,
        target_change_id: Optional[str] = None,
        inspect_openspec_fn: Optional[Callable[..., List[Dict[str, Any]]]] = None,
        inspect_adrs_fn: Optional[Callable[[Path], List[Dict[str, Any]]]] = None,
        inspect_spikes_fn: Optional[Callable[[Path], List[str]]] = None,
        inspect_review_fn: Optional[Callable[..., Optional[Dict[str, Any]]]] = None,
    ) -> Dict[str, Any]:
        if target_change_id is not None:
            validate_change_id(target_change_id)
        with cls.lock(repo_root):
            ledger_path = cls.get_ledger_path(repo_root)
            loaded = read_ledger_file(ledger_path)
            existing: Dict[str, Any] = loaded if isinstance(loaded, dict) and "changes" in loaded else {}

            changes: Dict[str, Any] = dict(existing.get("changes", {}))
            active_change_id = existing.get("active_change_id") or cls.get_active_change(repo_root)
            if not active_change_id and target_change_id:
                active_change_id = target_change_id

            packages = inspect_openspec_fn(repo_root, target_change=None) if inspect_openspec_fn else []
            adrs = inspect_adrs_fn(repo_root) if inspect_adrs_fn else []
            spikes = inspect_spikes_fn(repo_root) if inspect_spikes_fn else []

            # Re-read ledger state to capture any concurrent updates committed during workspace discovery
            latest_loaded = read_ledger_file(ledger_path)
            if isinstance(latest_loaded, dict) and "changes" in latest_loaded:
                for cid, cval in latest_loaded["changes"].items():
                    if cid not in changes:
                        changes[cid] = cval
                    elif isinstance(cval, dict) and cval.get("revision_counter", 0) > changes[cid].get("revision_counter", 0):
                        changes[cid] = cval
                if not active_change_id and latest_loaded.get("active_change_id"):
                    active_change_id = latest_loaded["active_change_id"]

            discovered_changes = [p["change"] for p in packages]
            if not discovered_changes:
                if active_change_id and changes.get(active_change_id, {}).get("evidence", {}).get("delivery", {}).get("status") != "ARCHIVED":
                    discovered_changes = [active_change_id]
                elif adrs:
                    discovered_changes = [adrs[0]["name"].replace(".md", "").lower()]
                else:
                    discovered_changes = ["default"]

            for change in discovered_changes:
                if change not in changes:
                    changes[change] = create_empty_change_entry(change)
                entry = changes[change]

                old_entry_snapshot = json.dumps({
                    "phase": entry.get("phase"),
                    "task_status": entry.get("task_status"),
                    "blockers": entry.get("blockers"),
                    "evidence": entry.get("evidence"),
                    "checkpoints": entry.get("checkpoints"),
                }, sort_keys=True)

                if entry.get("evidence", {}).get("delivery", {}).get("status") == "ARCHIVED":
                    entry["phase"] = "delivery"
                    continue

                matched_pkg = next((p for p in packages if p["change"] == change), None)
                if matched_pkg:
                    entry["task_status"]["total"] = matched_pkg["total_tasks"]
                    entry["task_status"]["completed"] = matched_pkg["completed_tasks"]
                    entry["task_status"]["pending"] = matched_pkg["pending_tasks"]
                    entry["task_status"]["next"] = matched_pkg["next_task"]
                    entry["task_status"]["in_progress"] = matched_pkg["next_task"]

                entry.setdefault("turns", [])
                entry.setdefault("evidence", {})
                entry["evidence"].setdefault("design", {"adr": None, "status": "PENDING"})
                entry["evidence"].setdefault("spike", {"status": "NONE", "verdict": None, "dir": None})
                entry["evidence"].setdefault("implementation", {"status": "PENDING", "tests_passed": None, "failed_count": 0})
                entry["evidence"].setdefault("simplify", {"debt_count": 0, "status": "PENDING"})
                entry["evidence"].setdefault("review", make_default_review_evidence())
                entry["evidence"].setdefault("delivery", {"status": "PENDING"})

                if adrs:
                    entry["evidence"]["design"]["adr"] = adrs[0]["name"]
                    entry["evidence"]["design"]["status"] = adrs[0].get("status")

                if spikes:
                    entry["evidence"]["spike"]["status"] = "ACTIVE"
                    entry["evidence"]["spike"]["dir"] = spikes[0]
                else:
                    if entry["evidence"]["spike"].get("status") == "ACTIVE":
                        entry["evidence"]["spike"]["status"] = "PASSED"

                review = inspect_review_fn(repo_root, change=change) if inspect_review_fn else None
                if review:
                    verdict = review.get("verdict") or review.get("status")
                    entry["evidence"]["review"]["verdict"] = verdict
                    entry["evidence"]["review"]["status"] = review.get("status")
                    entry["evidence"]["review"]["reviewer"] = review.get("reviewer")
                    entry["evidence"]["review"]["findings_count"] = review.get("findings_count", 0)
                    entry["evidence"]["review"]["critical_or_high_count"] = review.get("critical_or_high_count", 0)
                    entry["evidence"]["review"]["test_evidence_passed"] = review.get("test_evidence_passed")
                    entry["evidence"]["review"]["report_path"] = review.get("path") or review.get("report_file")
                    entry["evidence"]["review"]["snapshot_sha"] = review.get("snapshot_sha")
                    entry["evidence"]["review"]["snapshot_fingerprint"] = review.get("snapshot_fingerprint")
                    for key in ("is_judge", "is_envelope", "judge_report_valid", "judge_report_errors", "change"):
                        entry["evidence"]["review"][key] = review.get(key)

                chk_dir = get_checkpoints_dir(repo_root)
                if chk_dir.exists():
                    for cf in chk_dir.glob(f"{change}_*.json"):
                        cdata = read_json_file(cf)
                        if isinstance(cdata, dict):
                            gate_k = cdata.get("gate", cf.stem.replace(f"{change}_", ""))
                            entry["checkpoints"][gate_k] = cdata

                # Preserve explicit non-derived blockers (e.g. manual holds, design approval)
                explicit_blockers = [
                    b for b in entry.get("blockers", [])
                    if not (
                        b.startswith("Tests:")
                        or b.startswith("Design:")
                        or b.startswith("Spike active in ")
                        or is_review_blocker(b)
                    )
                ]

                existing_test_blockers = [b for b in entry.get("blockers", []) if b.startswith("Tests:")]
                if implementation_failed(entry["evidence"]["implementation"]):
                    failed_cnt = entry["evidence"]["implementation"].get("failed_count", 1)
                    t_blocker = f"Tests: {failed_cnt} test(s) failing"
                    if t_blocker not in existing_test_blockers:
                        existing_test_blockers.append(t_blocker)

                blockers: List[str] = list(existing_test_blockers)
                for eb in explicit_blockers:
                    if eb not in blockers:
                        blockers.append(eb)

                design_error = validate_design_approval(repo_root, change, entry) if matched_pkg else None
                if design_error:
                    blockers.append(f"Design: {design_error}")

                review_ev = entry["evidence"]["review"]
                if review_ev.get("critical_or_high_count", 0) > 0:
                    blockers.append(f"Review: {review_ev['critical_or_high_count']} unresolved CRITICAL/HIGH finding(s)")
                if review_ev.get("verdict") in {"FAIL", "FAILED", "REJECTED"}:
                    blockers.append(f"Review: verdict is {review_ev['verdict']}")
                if spikes:
                    blockers.append(f"Spike active in {spikes[0]}")

                deduped_blockers: List[str] = []
                for b in blockers:
                    if b not in deduped_blockers:
                        deduped_blockers.append(b)
                entry["blockers"] = deduped_blockers
                from .gates import determine_lifecycle_state
                entry["phase"] = determine_lifecycle_state(
                    GitClient().get_info(repo_root), adrs, [matched_pkg] if matched_pkg else [],
                    spikes, review_ev, active_change=entry,
                )[0]

                new_entry_snapshot = json.dumps({
                    "phase": entry.get("phase"),
                    "task_status": entry.get("task_status"),
                    "blockers": entry.get("blockers"),
                    "evidence": entry.get("evidence"),
                    "checkpoints": entry.get("checkpoints"),
                }, sort_keys=True)

                if entry.get("revision_counter", 0) == 0:
                    entry["revision_counter"] = 1
                elif new_entry_snapshot != old_entry_snapshot:
                    entry["revision_counter"] = entry.get("revision_counter", 1) + 1

            if not active_change_id and discovered_changes and discovered_changes != ["default"]:
                active_change_id = discovered_changes[0]

            new_ledger = {
                "version": 1,
                "active_change_id": active_change_id,
                "changes": changes,
            }
            cls.save(repo_root, new_ledger)
            return new_ledger

    @classmethod
    def load(
        cls,
        repo_root: Path,
        auto_sync: bool = True,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        with cls.lock(repo_root):
            ledger_path = cls.get_ledger_path(repo_root)
            data = read_ledger_file(ledger_path)
            if isinstance(data, dict) and "changes" in data:
                return data
            if auto_sync and sync_fn:
                return sync_fn(repo_root)
            return {"version": 1, "active_change_id": None, "changes": {}}

    @classmethod
    def mutate_change(
        cls,
        repo_root: Path,
        change_id: str,
        updater: Callable[[Dict[str, Any]], None],
        set_active: Optional[bool] = None,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        validate_change_id(change_id)
        # True selects this change; False clears it if selected; None preserves selection.
        with cls.lock(repo_root):
            ledger = cls.load(repo_root, auto_sync=False)
            ledger_path = cls.get_ledger_path(repo_root)
            if not ledger.get("changes") and not ledger_path.exists() and sync_fn:
                ledger = sync_fn(repo_root)
            changes = ledger.setdefault("changes", {})
            if change_id not in changes:
                changes[change_id] = create_empty_change_entry(change_id)
            entry = changes[change_id]
            updater(entry)
            entry["revision_counter"] = entry.get("revision_counter", 0) + 1
            if set_active:
                ledger["active_change_id"] = change_id
            elif set_active is False and ledger.get("active_change_id") == change_id:
                ledger["active_change_id"] = None
            cls.save(repo_root, ledger)
            return entry

    @classmethod
    def set_active_change(
        cls,
        repo_root: Path,
        change: str,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> None:
        validate_change_id(change)
        with cls.lock(repo_root):
            ledger = cls.load(repo_root, auto_sync=False)
            ledger_path = cls.get_ledger_path(repo_root)
            if not ledger.get("changes") and not ledger_path.exists() and sync_fn:
                ledger = sync_fn(repo_root)
            ledger["active_change_id"] = change.strip()
            cls.save(repo_root, ledger)

    @classmethod
    def record_review(
        cls,
        repo_root: Path,
        report_path_or_dict: Any,
        change_id: Optional[str] = None,
        parse_report_fn: Optional[Callable[[Path, Path], Dict[str, Any]]] = None,
        get_git_info_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
        attach_note_fn: Optional[Callable[..., Any]] = None,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        if isinstance(report_path_or_dict, (str, Path)):
            p = Path(report_path_or_dict)
            if not p.is_absolute():
                p = repo_root / p
            if parse_report_fn:
                report = parse_report_fn(p, repo_root)
            else:
                from .evidence import parse_review_report_file
                report = parse_review_report_file(p, repo_root)
        else:
            report = report_path_or_dict

        if get_git_info_fn is None:
            from .vcs import GitClient
            get_git_info_fn = GitClient().get_info

        if attach_note_fn is None:
            from .vcs import GitClient
            attach_note_fn = GitClient().attach_git_note_evidence

        cid = change_id or report.get("change") or cls.get_active_change(repo_root) or "default"

        def updater(entry: Dict[str, Any]) -> None:
            ev = entry["evidence"]["review"]
            ev["verdict"] = report.get("verdict")
            ev["status"] = report.get("status")
            ev["reviewer"] = report.get("reviewer")
            ev["findings_count"] = report.get("findings_count", 0)
            ev["critical_or_high_count"] = report.get("critical_or_high_count", 0)
            ev["test_evidence_passed"] = report.get("test_evidence_passed")
            ev["report_path"] = report.get("path") or report.get("report_file")
            ev["snapshot_sha"] = report.get("snapshot_sha")
            ev["snapshot_fingerprint"] = report.get("snapshot_fingerprint")
            for key in ("is_judge", "is_envelope", "judge_report_valid", "judge_report_errors", "change"):
                ev[key] = report.get(key)

            if get_git_info_fn and attach_note_fn:
                git_info = get_git_info_fn(repo_root)
                commit = git_info.get("commit")
                if commit:
                    note_oid = attach_note_fn(repo_root, commit, "review_report", report, change_id=cid)
                    if not note_oid:
                        raise RuntimeError("Review evidence could not be saved to Git notes; ledger unchanged")
                    ev["git_note_oid"] = note_oid

            blockers = [b for b in entry.get("blockers", []) if not is_review_blocker(b)]
            crit = ev.get("critical_or_high_count", 0)
            if crit > 0:
                blockers.append(f"Review: {crit} unresolved CRITICAL/HIGH finding(s)")
            if ev.get("verdict") in {"FAIL", "FAILED", "REJECTED"}:
                blockers.append(f"Review: verdict is {ev.get('verdict')}")
            entry["blockers"] = blockers

            git_info = get_git_info_fn(repo_root) if get_git_info_fn else {}
            approval_error = validate_review_approval(ev, cid, git_info)
            if approval_error:
                blockers.append(f"Review: {approval_error}")
            design_error = validate_design_approval(repo_root, cid, entry)
            blockers[:] = [b for b in blockers if not b.startswith("Design:")]
            if design_error:
                blockers.append(f"Design: {design_error}")
            from .gates import validate_delivery_readiness
            from .specs import OpenSpecRepository
            from .paths import resolve_change_path
            packages = OpenSpecRepository().inspect_openspec(repo_root, target_change=cid) if resolve_change_path(repo_root, cid).is_dir() else []
            package = packages[0] if packages else {"change": cid, "has_tasks": False, "total_tasks": 0}
            entry["phase"] = validate_delivery_readiness(ev, package, git_info, entry, design_error=design_error, spikes=inspect_spikes(repo_root))[0]

            turns = entry.setdefault("turns", [])
            turn_idx = len(turns) + 1
            turns.append({
                "turn_id": f"turn-{turn_idx:03d}",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "skill": "review",
                "harness": "generic",
                "execution_mode": report.get("execution_mode", "sequential"),
                "inputs": {
                    "report_path": ev.get("report_path"),
                    "reviewer": ev.get("reviewer"),
                },
                "evidence": {
                    "verdict": ev.get("verdict"),
                    "findings_count": ev.get("findings_count", 0),
                    "critical_or_high_count": ev.get("critical_or_high_count", 0),
                    "test_evidence_passed": ev.get("test_evidence_passed"),
                },
                "state_delta": {
                    "phase": entry["phase"],
                    "review_verdict": ev.get("verdict"),
                    "blockers_count": len(blockers),
                },
            })

        return cls.mutate_change(repo_root, cid, updater, sync_fn=sync_fn)

    @classmethod
    def approve_design(cls, repo_root: Path, change: str, fingerprint: str, approved_by: str) -> Dict[str, Any]:
        """Record an externally authorized approval of an explicitly reviewed snapshot."""
        if not isinstance(approved_by, str) or not approved_by.strip():
            raise ValueError("An approver identity is required")
        with cls.lock(repo_root):
            if fingerprint != design_fingerprint(repo_root, change):
                raise ValueError("Design changed: reviewed fingerprint does not match current design")
            def updater(entry: Dict[str, Any]) -> None:
                existing_app = entry.get("evidence", {}).get("design", {}).get("approval", {})
                if existing_app.get("fingerprint") == fingerprint and existing_app.get("approved_by") == approved_by.strip():
                    return
                entry.setdefault("evidence", {}).setdefault("design", {})["approval"] = {
                    "change": change, "fingerprint": fingerprint,
                    "approved_by": approved_by.strip(), "approved_at": time.time(),
                }
                entry["blockers"] = [b for b in entry.get("blockers", []) if not b.startswith("Design:")]
                turns = entry.setdefault("turns", [])
                turn_idx = len(turns) + 1
                turns.append({
                    "turn_id": f"turn-{turn_idx:03d}",
                    "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "skill": "design",
                    "harness": "generic",
                    "execution_mode": "sequential",
                    "inputs": {
                        "action": "approve_design",
                        "fingerprint": fingerprint,
                        "approved_by": approved_by.strip(),
                    },
                    "evidence": {
                        "design_fingerprint": fingerprint,
                        "approved_by": approved_by.strip(),
                    },
                    "state_delta": {
                        "design_approved": True,
                        "phase": entry.get("phase"),
                    },
                })
            return cls.mutate_change(repo_root, change, updater, set_active=None)

    @classmethod
    def record_test_run(
        cls,
        repo_root: Path,
        test_summary: Dict[str, Any],
        change_id: Optional[str] = None,
        get_git_info_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
        attach_note_fn: Optional[Callable[..., Any]] = None,
        notes_ref: str = "refs/notes/ship-evidence",
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        cid = change_id or cls.get_active_change(repo_root) or "default"
        if not isinstance(test_summary, dict):
            raise ValueError("Test summary must be a JSON object")
        passed = is_test_evidence_passing(test_summary)

        if get_git_info_fn is None:
            from .vcs import GitClient
            get_git_info_fn = GitClient().get_info

        if attach_note_fn is None:
            from .vcs import GitClient
            attach_note_fn = GitClient().attach_git_note_evidence

        def updater(entry: Dict[str, Any]) -> None:
            impl = entry["evidence"]["implementation"]
            impl["status"] = "PASSED" if passed else "FAILED"
            impl["tests_passed"] = passed
            impl["failed_count"] = test_summary.get("failed_count", 0)
            impl["command"] = test_summary.get("command")

            if get_git_info_fn and attach_note_fn:
                git_info = get_git_info_fn(repo_root)
                commit = git_info.get("commit")
                if commit:
                    if not attach_note_fn(repo_root, commit, "test_evidence", test_summary, change_id=cid):
                        raise RuntimeError("Test evidence could not be saved to Git notes; ledger unchanged")
                    impl["evidence_ref"] = notes_ref

            blockers = [b for b in entry.get("blockers", []) if not b.startswith("Tests:")]
            if not passed:
                blockers.append(f"Tests: {test_summary.get('failed_count', 1)} test(s) failing")
            entry["blockers"] = blockers

            turns = entry.setdefault("turns", [])
            turn_idx = len(turns) + 1
            turns.append({
                "turn_id": f"turn-{turn_idx:03d}",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "skill": "tdd",
                "harness": "generic",
                "execution_mode": "sequential",
                "inputs": {"command": test_summary.get("command")},
                "evidence": {
                    "tests_passed": passed,
                    "failed_count": test_summary.get("failed_count", 0),
                    "tests_run": test_summary.get("tests_run"),
                },
                "state_delta": {
                    "implementation_status": impl["status"],
                    "tests_passed": passed,
                },
            })

        return cls.mutate_change(repo_root, cid, updater, sync_fn=sync_fn)

    @classmethod
    def record_verification(
        cls,
        repo_root: Path,
        verification_records: Dict[str, Any],
        change_id: Optional[str] = None,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        cid = change_id or cls.get_active_change(repo_root) or "default"
        validate_change_id(cid)

        def updater(entry: Dict[str, Any]) -> None:
            verif = entry.setdefault("verification", {})
            has_failure = False
            failed_tiers = []

            for tier, rec in verification_records.items():
                if hasattr(rec, "to_dict"):
                    rec_dict = rec.to_dict()
                elif isinstance(rec, dict):
                    rec_dict = rec
                else:
                    rec_dict = {"verdict": str(rec)}
                verif[tier] = rec_dict
                if rec_dict.get("verdict") == "NOT_VERIFIED":
                    has_failure = True
                    failed_tiers.append(tier)

            blockers = [b for b in entry.get("blockers", []) if not b.startswith("Verification:")]
            if has_failure:
                blockers.append(f"Verification: {', '.join(failed_tiers)} verification tier(s) failed")
            entry["blockers"] = blockers

            turns = entry.setdefault("turns", [])
            turn_idx = len(turns) + 1
            turns.append({
                "turn_id": f"turn-{turn_idx:03d}",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "skill": "verification",
                "harness": "independent-verifier",
                "execution_mode": "sequential",
                "inputs": {"tiers": list(verification_records.keys())},
                "evidence": {k: (v.to_dict() if hasattr(v, "to_dict") else v) for k, v in verification_records.items()},
                "state_delta": {
                    "verification_passed": not has_failure,
                    "failed_tiers": failed_tiers,
                },
            })

        return cls.mutate_change(repo_root, cid, updater, sync_fn=sync_fn)

    @classmethod
    def resume_change(
        cls,
        repo_root: Path,
        change_id: Optional[str] = None,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        """Clear Halt blockers and resume workflow execution after human intervention."""
        cid = change_id or cls.get_active_change(repo_root) or "default"
        validate_change_id(cid)

        def updater(entry: Dict[str, Any]) -> None:
            entry["blockers"] = [b for b in entry.get("blockers", []) if not b.startswith("Halt:")]
            turns = entry.setdefault("turns", [])
            turn_idx = len(turns) + 1
            turns.append({
                "turn_id": f"turn-{turn_idx:03d}",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "skill": "human",
                "harness": "human-supervisor",
                "execution_mode": "manual",
                "inputs": {"action": "resume", "cleared_halt": True},
                "evidence": {"resumed": True},
                "state_delta": {"halt_cleared": True},
            })

        return cls.mutate_change(repo_root, cid, updater, sync_fn=sync_fn)

    @classmethod
    def record_turn(
        cls,
        repo_root: Path,
        turn_data: Dict[str, Any],
        change_id: Optional[str] = None,
        sync_fn: Optional[Callable[[Path], Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        from .turns import validate_turn_record
        validate_turn_record(turn_data)
        if change_id and turn_data.get("change_id") not in (None, change_id):
            raise ValueError("Turn change_id does not match the selected change")
        cid = change_id or turn_data.get("change_id") or cls.get_active_change(repo_root) or "default"
        validate_change_id(cid)

        with cls.lock(repo_root):
            def updater(entry: Dict[str, Any]) -> None:
                turns = entry.setdefault("turns", [])
                turn_idx = len(turns) + 1
                record = {
                    "turn_id": turn_data.get("turn_id") or f"turn-{turn_idx:03d}",
                    "timestamp": turn_data.get("timestamp") or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "skill": turn_data.get("skill", "unknown"),
                    "harness": turn_data.get("harness", "generic"),
                    "execution_mode": turn_data.get("execution_mode", "sequential"),
                    "inputs": turn_data.get("inputs", {}),
                    "evidence": turn_data.get("evidence", {}),
                    "state_delta": turn_data.get("state_delta", {}),
                }
                turns.append(record)

            return cls.mutate_change(repo_root, cid, updater, sync_fn=sync_fn)

    @classmethod
    def get_turns(cls, repo_root: Path, change_id: Optional[str] = None) -> List[Dict[str, Any]]:
        with cls.lock(repo_root):
            ledger = cls.load(repo_root, auto_sync=False)
            cid = change_id or ledger.get("active_change_id")
            if not cid and ledger.get("changes"):
                cid = list(ledger["changes"].keys())[0]
            if not cid:
                return []
            entry = ledger.get("changes", {}).get(cid, {})
            return list(entry.get("turns", []))

    @classmethod
    def clear_active_change(cls, repo_root: Path, change: Optional[str] = None) -> None:
        with cls.lock(repo_root):
            state_file = cls.get_ledger_path(repo_root)
            if state_file.exists():
                data = read_ledger_file(state_file)
                if isinstance(data, dict) and (change is None or data.get("active_change_id") == (change.strip() if change else None)):
                    data["active_change_id"] = None
                    cls.save(repo_root, data)

    @classmethod
    def get_coordination(cls, repo_root: Path, change_id: Optional[str] = None) -> Dict[str, Any]:
        """Get the multi-agent coordination data (leases, handoffs) for a change."""
        with cls.lock(repo_root):
            ledger = cls.load(repo_root, auto_sync=False)
            cid = change_id or ledger.get("active_change_id")
            if not cid and ledger.get("changes"):
                cid = list(ledger["changes"].keys())[0]
            if not cid:
                return {"leases": {}, "handoffs": []}
            entry = ledger.get("changes", {}).get(cid, {})
            return dict(entry.get("coordination", {"leases": {}, "handoffs": []}))

get_ledger_path = FileLedgerStore.get_ledger_path
ledger_lock = FileLedgerStore.lock
get_active_change = FileLedgerStore.get_active_change
set_active_change = FileLedgerStore.set_active_change
clear_active_change = FileLedgerStore.clear_active_change
load_ledger = FileLedgerStore.load
save_ledger = FileLedgerStore.save
mutate_change_state = FileLedgerStore.mutate_change
record_review_to_ledger = FileLedgerStore.record_review
record_test_run_to_ledger = FileLedgerStore.record_test_run
record_verification_to_ledger = FileLedgerStore.record_verification
record_turn_to_ledger = FileLedgerStore.record_turn
resume_change_in_ledger = FileLedgerStore.resume_change
get_turns_from_ledger = FileLedgerStore.get_turns
sync_ledger_from_workspace = FileLedgerStore.sync_from_workspace

